- hosts: all
  vars_files:
    - defaults/main.yml
    - vars/main.yml
  tasks:
    - include: tasks/main.yml
      
    - name: Send email on success
      mail:
        host: smtp.mailgun.org
        username: "{{ email_username }}"
        password: "{{ email_password }}"
        to: ross@influxdb.com
        from: root@repos.influxdata.com
        subject: "[bot] - Nightly Build Generated"
        body: "Hello, I wanted to let you know that the nightly builds have been generated.\n\n{{ ansible_date_time.iso8601 }}"
      when: email_username is defined and email_username != None and email_password is defined and email_password != None and build_output.rc == 0

    - name: Send email on failure
      mail:
        host: smtp.mailgun.org
        username: "{{ email_username }}"
        password: "{{ email_password }}"
        to: ross@influxdb.com
        from: root@repos.influxdata.com
        subject: "[bot] - Nightly Build Failed"
        body: "Hello, I wanted to let you know that the nightly builds encountered a failure. The full logs are attached.\n\n{{ ansible_date_time.iso8601 }}"
        attach: /var/log/influxdb-nightly-build.log
      when: email_username is defined and email_username != None and email_password is defined and email_password != None and build_output.rc != 0
    