- hosts: all
  vars_files:
    - defaults/main.yml
    - vars/main.yml
  tasks:
    - include: tasks/main.yml
      build_repo_url: https://github.com/influxdata/telegraf
      build_master_version: 0.11.0
      build_go_version: 1.5.3
      build_script: scripts/build.py
