---

- name: Send email on success
  mail:
    host: "{{ email_hostname }}"
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    to: "{{ email_to }}"
    from: "{{ email_from }}"
    subject: "[bot] - {{ build_package_name }} - Build Success"
    body: "Hello, I wanted to let you know that the {{ build_package_name|title }} {% if build_nightly %}nightly {% endif %}builds have been generated.\n\n{{ ansible_date_time.iso8601 }}"
  when: email_username is defined and email_username != None and email_password is defined and email_password != None and build_output.rc == 0

- name: Send email on failure
  mail:
    host: "{{ email_hostname }}"
    username: "{{ email_username }}"
    password: "{{ email_password }}"
    to: "{{ email_to }}"
    from: "{{ email_from }}"
    subject: "[bot] - {{ build_package_name }} - Build Failure"
    body: "Hello, I wanted to let you know that the {{ build_package_name|title }} {% if build_nightly %}nightly {% endif %} builds encountered a failure during the build process. Here is the output from the run:\n\n{{ build_output.stdout_lines|join('\n') }}\n\n{{ ansible_date_time.iso8601 }}"
  when: email_username is defined and email_username != None and email_password is defined and email_password != None and build_output.rc != 0
