---

- name: Check for GVM
  stat:
    path: ~/.gvm
  register: gvm_installed

- name: Download GVM install script
  get_url:
    url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
    dest: /tmp
    mode: 0700
  when: gvm_installed.stat.exists is defined and gvm_installed.stat.exists == False

- name: Install GVM
  command: /tmp/gvm-installer
  when: gvm_installed.stat.exists is defined and gvm_installed.stat.exists == False  
  
- name: Check for Go
  stat:
    path: "{{ ansible_env.HOME }}/.gvm/gos/go{{ go_version }}"
  register: go_installed
  
- name: Install Go
  shell: . {{ ansible_env.HOME }}/.bashrc && {{ ansible_env.HOME }}/.gvm/bin/gvm install go{{ go_version }} --binary
  environment:
    GVM_ROOT: "{{ ansible_env.HOME }}/.gvm"
  when: go_installed.stat.exists is defined and go_installed.stat.exists == False
